### ISSUE TITLE
carousel controls

### ISSUE THREAD

**Issue by JessicaBrown** [BlackrockDigital/startbootstrap-full-slider#1]
I used the exact code and have all my dependencies injected. When i click the > button to go to the next slide it will not go past slide two. When i click the < button to go to the previous slide it just shows slide 3. The Indicators work its just the controls having issues. Please Help!!!

**Comment by MakiNavaja** [comment]
Its NOT a genious proposal but I usualy do 2 projects and copy\paste the parts that dont work to one another. Sometimes I dont know how it gets better but just by deleteing whole chunks (i was thinkig were ok) and paste new ones ( the same?) things suddenly get better... I guess the holy Ghost...

**Comment by JessicaBrown** [comment]
For the love of code lol Thanks for the response!
