### ISSUE TITLE
Auto rotation not working in carousel

### ISSUE THREAD

**Issue by Gajendrasinh** [BlackrockDigital/startbootstrap-full-slider#3]
Same code i have use 

<script type="text/javascript">
  $(document).ready(function() {
    $('.carousel').carousel({
      interval: 12000
    })
  });
</script>

i have increase speed. when i click on next then after rotation is start normal

**Comment by davidtmiller** [comment]
Check out the carousel docs at http://getbootstrap.com and see if you can auto-play and auto-rotate using their scripts.
