### ISSUE TITLE
Slides are flickering Black/White Background

### ISSUE THREAD

**Issue by rushingJustice** [BlackrockDigital/startbootstrap-full-slider#5]
My slides are flickering in such a way that the white/black default background image is showing every now and then when I click through the carousel on iOS. I've hunted through the internet trying to fix this issue! Any thoughts?

**Comment by ace-gabriel** [comment]
How do you solve this problem?

**Comment by davidtmiller** [comment]
This should be fixed up in Bootstrap 4's release.
